# Generated by Django 3.0 on 2025-07-17 21:37

from django.db import migrations


def transfer_profiles_data(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')

    for old_prof in OldProfile.objects.all():
        NewProfile.objects.create(
            user=old_prof.user,
            favorite_city=old_prof.favorite_city
        )


def reverse_transfer(apps, schema_editor):
    NewProfile = apps.get_model('profiles', 'Profile')
    NewProfile.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_profiles_data, reverse_transfer),
    ]
