# Generated by Django 3.0 on 2025-07-17 21:24

from django.db import migrations


def transfer_lettings_data(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewAddress = apps.get_model('lettings', 'Address')
    NewLetting = apps.get_model('lettings', 'Letting')

    # Copy Addresses
    address_map = {}
    for old_addr in OldAddress.objects.all():
        new_addr = NewAddress.objects.create(
            number=old_addr.number,
            street=old_addr.street,
            city=old_addr.city,
            state=old_addr.state,
            zip_code=old_addr.zip_code,
            country_iso_code=old_addr.country_iso_code,
        )
        address_map[old_addr.id] = new_addr

    # Copy Lettings
    for old_let in OldLetting.objects.all():
        NewLetting.objects.create(
            title=old_let.title,
            address=address_map[old_let.address_id]
        )


def reverse_transfer(apps, schema_editor):
    NewAddress = apps.get_model('lettings', 'Address')
    NewLetting = apps.get_model('lettings', 'Letting')
    NewAddress.objects.all().delete()
    NewLetting.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_lettings_data, reverse_transfer),
    ]
