# Generated by Django 3.0 on 2025-07-17 21:39

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('lettings', '0002_migrate_lettings_data'),  # Ensure data is copied first
        ('profiles', '0002_migrate_profiles_data'),
    ]

    operations = [
        migrations.DeleteModel(name='Address'),
        migrations.DeleteModel(name='Letting'),
        migrations.DeleteModel(name='Profile'),
    ]
